markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# These allow the documentation to be updated with new releases of Tachyon.
TACHYON_RELEASED_VERSION: 0.8.2
TACHYON_MASTER_VERSION_SHORT: 0.9.0-SNAPSHOT

defaults:
  -
    scope:
      path: "en"
    values:
      lang: "English"
      languagePriority: "0"
  -
    scope:
      path: "cn"
    values:
      lang: "中文"
      languagePriority: "1"
